### ISSUE TITLE
Needs more love

### ISSUE THREAD

**Issue by thany** [nicolo-ribaudo/brackets-svg-font#1]
It's a good start, but this extension needs a bit more love before it's fairly usable.

For starters:
- It doesn't pick up the theme colours
- Some TTF's display glyphs in the default Times New Roman font, instead of in the selected font
- As for SVG fonts, they always display glyphs in the default font
- I've got a icon font, generated with IcoMoon, that just doesn't load at all (the loader keeps animating forever)
- Missing support for WOFF and EOT

I can privately send you some font files to test with, as the font files in question are commercial ones and shouldn't roam too freely ;)

**Comment by thany** [comment]
But worse, I cannot edit an SVG at all now (I'm seeing just a loading animation, forever). So I have no choice but to uninstall this extension for now.

**Comment by nicolo-ribaudo** [comment]
Thanks for the feedback, @thany 

> - It doesn't pick up the theme colours

Done (commit 70b4cf9bf43681739a0939f30fd65b7ce092f946)

> - As for SVG fonts, they always display glyphs in the default font
- Are these glyphs multicharacter glyphs?
  (Something like `<glyph unicode="more than one character" ... >`)
- Are these glyphs shown correctly in Chrome?

> - I've got a icon font, generated with IcoMoon, that just doesn't load at all (the loader keeps animating forever)

Is it a `ttf` font? This extension uses [ttf2svg](https://github.com/qdsang/ttf2svg) to convert fonts to svg (so they can be parsed), but it doesn't work very well. I was thinking about supporting only `svg` fonts by default and let users to open other font files if they have [FontForge](http://fontforge.github.io) - The best font converter I've ever seen -  installed.

If it is a `svg` font, can you send it me? (You can get my email in my profile)

> But worse, I cannot edit an SVG at all now (I'm seeing just a loading animation, forever)

Fixed - 8922693da6f633936f376b598c28ed60475888fd

**Comment by nicolo-ribaudo** [comment]
> - Some TTF's display glyphs in the default Times New Roman font, instead of in the selected font

Fixed

> - As for SVG fonts, they always display glyphs in the default font

Fixed 

> - Missing support for WOFF and EOT

Added support for WOFF and OTF fonts. I don't know how to add support for EOT fonts, because FontForge (which this extension uses) doesn't open them.
