### ISSUE TITLE
Installation fails using Brackets Extensions Registry

### ISSUE THREAD

**Issue by glepretre** [nicolo-ribaudo/brackets-svg-font#3]
![selection_009](https://cloud.githubusercontent.com/assets/5930831/7159953/516ee1c2-e386-11e4-9638-b1a161dd2827.png)
![selection_010](https://cloud.githubusercontent.com/assets/5930831/7159952/515630be-e386-11e4-8486-8b6fa7a554d6.png)

Please tell me if you need more debug info :wink:

**Comment by nicolo-ribaudo** [comment]
What version of Brackets are you using? It looks like you have an old webikt version...

If you type `Symbol` in the Brackets' console,  does it print something like `function () { [native code] }`?

**Comment by glepretre** [comment]
I'm running 

> Release 1.2 experimental build 1.2.0-15697 (release 8f82e2a97) 
> build timestamp: Tue Feb 24 2015 21:16:20 GMT-0800

When I type `Symbol` in the console I get `Symbol is not defined` :disappointed: of course...

My OS is Linux Mint Debian Edition - wheezy (stable), it's possible that my packages are not the latest available... but brackets had all its dependencies satisfied to be installed :smirk: 

What do you think I need to upgrade?

**Comment by nicolo-ribaudo** [comment]
> What do you think I need to upgrade?

Nothing :wink: (I'm using Brackets 1.2 too)

I think Brackets for Linux uses an older version of cef...
Can you type `navigator.userAgent` in Brackets' console and check what version of Chrome is used in Brackets?

**Comment by nicolo-ribaudo** [comment]
Fixed (I hope)

Can you download the extension from the repo (click on "Download ZIP") and try to install it?

**Comment by nicolo-ribaudo** [comment]
@glepretre Can you install the last version? (Available from the Extension Manager)

**Comment by glepretre** [comment]
> Can you type navigator.userAgent in Brackets' console and check what version of Chrome is used in Brackets?

`"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.80 Safari/537.36"`

**Comment by glepretre** [comment]
I successfully installed the latest version!... but it's not working yet

![selection_001](https://cloud.githubusercontent.com/assets/5930831/7225669/45b5ec9a-e741-11e4-9d5c-7b41bdb2e157.png)

I have the same message for a `.woff` font

**Comment by nicolo-ribaudo** [comment]
I finally installed Ubuntu to test the extension :wink: 

Does it work now?
https://drive.google.com/file/d/0B8oCEY0KhtmPbWNYbEowSWE0SEU/view?usp=sharing

**Comment by glepretre** [comment]
> I finally installed Ubuntu to test the extension :wink: 

Wow, I did not expect you to change your OS! (...but if you were on Windows before, be careful, you might soon like linux :smile:)

I successfully installed this beta, it opened fontforge, but does not seem to open it again at brackets startup.

It looks like this:

![selection_001](https://cloud.githubusercontent.com/assets/5930831/7247753/32e25e6a-e80d-11e4-813c-e5950e0d3321.png)

This installation issue is solved. You should open another one if you want to improve the rendering. 

Now I can say your extension is :cool: And thank you for your time and work, I know what it takes to maintain an open source project :wink:
